sudo: false
language: python
matrix:
  include:
    - python: 3.7
      dist: xenial
before_install:
  - pip install poetry
install:
script:
  - echo 'No tests yet.'
deploy:
  provider: script
  script: poetry publish --build -u $PYPI_USER -p $PYPI_PASSWORD
  on:
    tags: true
    condition: "$TRAVIS_PYTHON_VERSION == 3.7"
